version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 18.x
    pre_build:
        commands:
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - ng build --configuration production
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: dist
    discard-paths: no
